language: csharp
dotnet: 2.1.3
dist: trusty
mono: none

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.5

script:
  - dotnet test test/NeinLinq.Tests --configuration Release --framework netcoreapp1.1
  - dotnet test test/NeinLinq.Tests --configuration Release --framework netcoreapp2.0
